### ISSUE TITLE
Fix contractAddress based on web3 definition of value

### ISSUE THREAD

**Issue by emaG3m** [nearprotocol/near-web3-provider#15]
(consolidating issue from: https://github.com/summa-tx/near-web3-provider/issues/14)

**Comment by emaG3m** [comment]
@barbaraliau I transfered this issue from the summa repo. Has this been fixed? To me it seems to be behaving correctly..

**Comment by barbaraliau** [comment]
Yes, I think this has been fixed.

**Comment by barbaraliau** [comment]
Resolved. Closing issue.
