### ISSUE TITLE
Nonce Discrepancy?

### ISSUE THREAD

**Issue by emaG3m** [nearprotocol/near-web3-provider#27]
`web3.eth.getTransactionCount`  returns how many evm transactions have taken place from an address.
`web3.eth.getTransaction` returns an object with the nonce of how many near transactions (which includes evm transactions) have taken place up until this transaction. So this number will always be higher.

Should these values line up? Do we need to track a separate evm nonce?

**Comment by emaG3m** [comment]
@prestwich

**Comment by prestwich** [comment]
hmmm. I think it's fine if get transaction returns a higher nonce. Do we already have documentation of rough edges like this?

**Comment by emaG3m** [comment]
no, would have to update README to be more specific about this

**Comment by prestwich** [comment]
Cool. let's make a generic heading in the readme where we can list things like this. Something like "Behavior differences from Ethereum"

**Comment by emaG3m** [comment]
if you look at my latest PR I'm also finding some confusion as to when a blockhash should be base58 as opposed to hex. SO I guess that's kind of similar to this issue

**Comment by emaG3m** [comment]
I guess I'm just left wondering why we're tracking a separate evm nonce. Why not just reference the near nonce. And if we do need to track an evm nonce, it is not being incremented on simple transfers, so I'm guessing that's a bug?

**Comment by prestwich** [comment]
the only reason to track the evm nonce is for contract deployment. It's used in address calculation for new contracts (to match Ethereum behavior). We can't use the near nonce for that because evm contracts won't have one

Every other function of the nonce is covered by near nonces

**Comment by emaG3m** [comment]
feature covered in lines 136 & 506 of README in PR: https://github.com/nearprotocol/near-web3-provider/pull/30

Might want to double check I articulated this correctly
