### ISSUE TITLE
Consider putting relevant methods under own web3.near module

### ISSUE THREAD

**Issue by barbaraliau** [nearprotocol/near-web3-provider#39]
This is something that is worth thinking about. A user would need two instances of `web3` in order to get both Near block/tx information and Ethereum block/tx information, since we overwrite the original `web3.eth` methods. It would be better to move relevant methods into its own module under `web3.near` to prevent collisions. We could also return back the data in a format we prefer (e.g. `b58` vs hex), and remove unused properties that `web3.eth` forces us to return. We could keep the same method names for consistency and to know which methods correspond with each other.

Initial conversation: https://github.com/nearprotocol/near-web3-provider/pull/37#discussion_r460225532

**Comment by prestwich** [comment]
the provider wraps an instance of nearlib right? shouldn't the near calls be made on nearlib?

**Comment by barbaraliau** [comment]
It does internally, yes. We rewrote the `web3.eth` methods to return Near information instead of eth. I'm proposing we move those relevant methods to `web3.near`.

For example, using the `NearProvider` as currently written, the method: `web3.eth.getGasPrice` returns the current gas in yoctoNEAR. Instead of doing that, move this functionality into `web3.near.getGasPrice` to return the current gas price in yoctoNEAR.

It's not a hard change, but it is a big API change. Conceptually I think it makes more sense to have anything to do with the `Near` chain be under `web3.near`.

I don't think this is an urgent matter, but it might be worth considering for the future.

**Comment by prestwich** [comment]
I think this moves a long way from project goals. The ideal devex is that you can swap the provider and make no other changes to the existing eth app. This means accessing near via `web3.eth`

**Comment by barbaraliau** [comment]
Gotcha. That makes sense. Diving into the extension module made it seem like they want you to create new modules for things like this.

**Comment by barbaraliau** [comment]
Closing this issue then, as it is beyond project scope.

**Comment by barbaraliau** [comment]
@prestwich what about for new methods that are added? Does it make sense to keep those under `web3.eth` or would that be where it makes sense to put it under `web3.near`?

**Comment by prestwich** [comment]
ya, I think that'd be good. particularly, we need something that registers an ECDSA alias

**Comment by barbaraliau** [comment]
Sounds good. Any new methods will put under `web3.near`

**Comment by emaG3m** [comment]
I'll revert the latest commit on my latest PR to accommodate this.
