### ISSUE TITLE
Transaction receipt fails to return when calling contract

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-web3-provider#8]
Getting the following error when calling a contract function in web3js. The TX seems to execute (according to explorer), but the receipt is failing to return. 

https://explorer.nearprotocol.com/transactions/8GbnSufdmz6aEJ3a9qER9RevLRmXbH69gapsRShwZrpe

Code:
```javascript
const response = await contract.methods.get().send({ from: accounts[0] });
```

Error:
```
index.js:58 Uncaught (in promise) Error: Failed to check for transaction receipt:
{}
    at Object._fireError (index.js:58)
    at index.js:271
```

**Comment by prestwich** [comment]
this message typically means that the receipt translation logic errored, and failed to return a receipt. Can you provide more tx details so I can reproduce?

**Comment by kcole16** [comment]
Picking this up again!

Have everything you need to reproduce in this repo: https://github.com/kcole16/evm-example

Contracts deployed to account "verystable" on testnet. Included the build file with the address in the repo so you don't need to deploy anything.

**Comment by barbaraliau** [comment]
Thanks for putting that together. I’ll look into it some more. I’ve got a
PR coming that should fix this issue (if it is what I’m thinking of).

**Comment by emaG3m** [comment]
Can this issue be closed?

**Comment by barbaraliau** [comment]
This should be good. Closing issue.
